# delivery-pipeline.yaml

apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: my-paralle-demo
description: main application pipeline
serialPipeline:
  stages:
  - targetId: qsprod-multi
    profiles: []
    deployParameters:
    - values:
        replicaCount: "1"
      matchTargetLabels:
        label1: label1
    - values:
        replicaCount: "2"
      matchTargetLabels:
        label2: label2
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: qsprod-multi
description: production clusters
multiTarget:
  targetIds: [qsprod-a, qsprod-b]
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: qsprod-a
  labels:
    label1: label1
description: production cluster 2
gke:
  cluster: projects/${PROJECT}/locations/%{REGION}/clusters/${CLUSTER_1_NAME}
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: qsprod-b
  labels:
    label2: label2
description: production cluster 3
gke:
  cluster: projects/${PROJECT}/locations/%{REGION}/clusters/${CLUSTER_1_NAME}
